export default async function Index() {
  const res = await fetch(process.env.API_URL!);
  const { message } = await res.json();
  console.log(message)
  return (
    <>
      <h1>Welcome to frontend {message}!</h1>
      <p>Generated by create-nx-workspace</p>
    </>
  );
}
